### ISSUE TITLE
Deep Software Standby mode possible for an Arduino UNO R4 Minima board?

### ISSUE THREAD

**Issue by FUEL4EP** [TriodeGirl/Arduino-UNO-R4-Wake_from_interrupt-and-system-clock-switching#1]
Hi Susan,

Thanks for your Arduino UNO R4 example code. It is really helpful to get familiar with the Arduino Renesas RA4M1 core.

Questions:

a) Is there a way to enter the 'Deep Software Standby mode' of an Arduino UNO R4 Minima ?
b) if yes, which supply currents can be achieved in  'Deep Software Standby mode' ?
c) Is it possible to further reduce the supply currents, e.g. by de-soldering the LEDs?

I am wondering an Arduino UNO R4 Minima could be used as a sensor node with a battery supply. I am used to do this for ATMega284P boards. This requires supply currents of <10 uA in deep sleep mode.

Thanks in advance.

Best regards,

Ewald

**Comment by TriodeGirl** [comment]
Hi, thanks for your questions.
a) Yes there is, but it is complicated and one really needs to be using the resources provided by Renesas with their e2studio. The code I show is an easy way to get into the basic low power state within the scope of the Arduino IDE.
b) One should be able to get very low powers, but as per a) depends. The RA4M1 datasheet section **10. Low Power Modes** gives the info.
[https://www.renesas.com/us/en/document/mah/renesas-ra4m1-group-users-manual-hardware?r=1054146](url)
c) LEDS, yes absolutely. The prime culprit is the power ON LED which takes a whopping 8mA or more. I rewired the connection to USB +5V input before the Schottky diode, so the LED is only one when the board is connected to a computer. Plus changed the series-resistor. The other LED on P13 also needs attention, as it significantly loads the SCLK line beyond the RA4M1's pin specification.
Hope this helps.
Best,
Susan.

**Comment by FUEL4EP** [comment]
Thanks a lot for your precise and swift answers, Susan.
